version: "3.8"

volumes:
  mysql:

networks:
  psi:

services:
  database:
    container_name: database
    image: mariadb:latest
    env_file: ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
      - ./files/database-init.d:/docker-entrypoint-initdb.d
    networks:
      - psi

  website:
    container_name: website
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - psi
    depends_on:
      - database
