version: "3.8"

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql:


services:
  database:
    image: mariadb:latest
    env_file: ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - mysql-network
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
